# 开发框架头文件路径
PUBINCL = -I/project/public

# 开发框架cpp文件名
PUBCPP = /project/public/_public.cpp

all:demo03 demo04 demo05 demo06

demo03: demo03.cpp
	g++ -g -o demo03 demo03.cpp $(PUBINCL) $(PUBCPP)

demo04: demo04.cpp
	g++ -g -o demo04 demo04.cpp $(PUBINCL) $(PUBCPP)

demo05: demo05.cpp
	g++ -g -o demo05 demo05.cpp $(PUBINCL) $(PUBCPP)

demo06: demo06.cpp
	g++ -g -o demo06 demo06.cpp $(PUBINCL) $(PUBCPP)